// ДАНІ ПРОЄКТІВ
const projectsData = [
  { "id": "Age-of-Wonders-4",
  "title": "Age of Wonders 4",
  "cover": "assets/Age_of_Wonders_4.webp",
  "logo": "assets/Age_of_Wonders_4_logo.webp",
  "status": "in-progress",
  "progress": 97,
  "progress_text": 97,
  "progress_fonts": 100,
  "desc": "Фентезійна 4X стратегія з глибокою системою створення фракцій і тактичними боями. Повна локалізація інтерфейсу та всіх текстів українською.",
  "desc_en": "Fantasy 4X strategy with deep faction customization and tactical battles. Full UI and text localization in Ukrainian.",
  "github": "https://github.com/EYELESS-UA/Age-of-Wonders-4-Ukrainian-Localization",
  "lkb": "https://lbklauncher.com/games/age_of_wonders_4/eyeless",
  "cta": { "type": "link",
  "label": "Завантажити",
  "label_en": "Download",
  "url": "https://steamcommunity.com/sharedfiles/filedetails/?id=3391786639",
  "primary": true }, "videos": [ "https://www.youtube.com/watch?v=VzfgLRdyP3g" ],
  "gallery": ["assets/screenshot/Age-of-Wonders-4/screenshot_00.webp",
  "assets/screenshot/Age-of-Wonders-4/screenshot_01.webp",
  "assets/screenshot/Age-of-Wonders-4/screenshot_02.webp",
  "assets/screenshot/Age-of-Wonders-4/screenshot_03.webp"] 
  },

  { "id": "Arx-Libertatis",
    "title": "Arx Fatalis",
    "cover": "assets/Arx_Fatalis.webp",
    "logo": "https://raw.githubusercontent.com/EYELESS-UA/EYELESS-UA.github.io/refs/heads/main/assets/Arx_Fatalis_Logo.webp",
    "status": "done",
    "progress": 100,
    "progress_text": 100,
    "desc": "Класична рольова гра від першої особи з елементами immersive sim. Повна українська локалізація інтерфейсу, діалогів та написів.",
    "desc_en": "Classic first-person RPG with immersive sim elements. Full Ukrainian localization of UI, dialogues and text.",
    "github": "https://github.com/EYELESS-UA/Arx-Libertatis-Ukrainian-localization",
    "lkb": "",
    "cta": { "type": "link",
    "label": "Завантажити",
    "label_en": "Download",
    "url": "https://github.com/EYELESS-UA/Arx-Libertatis-Ukrainian-localization/releases/download/v1.0.0/Arx.Libertatis-Ukrainian.localization.v1.0.0.zip",
    "primary": true },
    "videos": [ "https://www.youtube.com/watch?v=KMm22gl2dJo" ],
    "gallery": [] 
  },

  { "id": "Dream_Engines_Nomad_Cities",
    "title": "Dream Engines: Nomad Cities",
    "cover": "assets/Dream_Engines_Nomad_Cities.webp",
    "logo": "assets/Dream_Engines_Nomad_Cities_Logo.webp",
    "status": "done",
    "progress": 100,
    "progress_text": 100,
    "desc": "Стратегія виживання з мандрівними містами у світі, що зникає. Повна українська локалізація всіх ігрових текстів та інтерфейсу.",
    "desc_en": "Survival strategy with nomadic cities in a vanishing world. Full Ukrainian localization of all game texts and UI.",
    "github": "https://github.com/EYELESS-UA/Dream-Engines-Nomad-Cities-Ukrainian-localization",
    "lkb": "",
    "cta": { "type": "link",
    "label": "Завантажити",
    "label_en": "Download",
    "url": "https://steamcommunity.com/sharedfiles/filedetails/?id=3258925888",
    "primary": true },
    "videos": ["https://www.youtube.com/watch?v=lE--8CJ5akA"],
    "gallery": ["assets/screenshot/Dream_Engines_Nomad_Cities/screenshot_00.webp",
    "assets/screenshot/Dream_Engines_Nomad_Cities/screenshot_01.webp",
    "assets/screenshot/Dream_Engines_Nomad_Cities/screenshot_02.webp",
    "assets/screenshot/Dream_Engines_Nomad_Cities/screenshot_03.webp",
    "assets/screenshot/Dream_Engines_Nomad_Cities/screenshot_04.webp",
    "assets/screenshot/Dream_Engines_Nomad_Cities/screenshot_05.webp",
    "assets/screenshot/Dream_Engines_Nomad_Cities/screenshot_06.webp"] 
      },

  { "id": "The-Guild-3",
    "title": "The Guild 3",
    "cover": "assets/TheGuild3.webp",
    "logo": "assets/TheGuild3_Logo.webp",
    "status": "done",
    "progress": 100,
    "progress_text": 100,
    "desc": "Життєвий симулятор у середньовічній Європі з династичною системою. Повна локалізація інтерфейсу, квестів та діалогів українською.",
    "desc_en": "Life simulation in medieval Europe with dynasty system. Full localization of UI, quests and dialogues in Ukrainian.",
    "github": "https://github.com/EYELESS-UA/TheGuild3_Ukrainian_localization",
    "lkb": "https://lbklauncher.com/games/the_guild_3/eyeless",
    "cta": { "type": "link",
    "label": "Завантажити",
    "label_en": "Download",
    "url": "https://steamcommunity.com/sharedfiles/filedetails/?id=3507960492",
    "primary": true },
    "steam": "",
    "videos": ["https://www.youtube.com/watch?v=9zLDr6J7qSo"],
    "gallery": [] 
    },

  { "id": "AgeofWondersPlanetfall",
    "title": "Age of Wonders Planetfall",
    "cover": "assets/Age_of_Wonders_Planetfall.webp",
    "logo": "https://raw.githubusercontent.com/EYELESS-UA/EYELESS-UA.github.io/refs/heads/main/assets/Age_of_Wonders_Planetfall_Logo.webp",
    "status": "planned",
    "progress": 0,
    "progress_text": 0,
    "desc": "Науково-фантастична 4X стратегія зі зруйнованим галактичним імперіумом. Планується повна українська локалізація.",
    "desc_en": "Sci-fi 4X strategy with a collapsed galactic imperium. Full Ukrainian localization planned.",
    "lkb": "",
    "cta": { "type": "link",
    "label": "Завантажити",
    "label_en": "Download",
    "url": "https://steamcommunity.com/sharedfiles/filedetails/?id=3391786639",
    "primary": true },
    "videos": [ "https://www.youtube.com/watch?v=p0xHfIbj6b0" ],
    "gallery": [] 
    },

//  { "id": "HellishQuart",
//    "title": "Hellish Quart",
//    "cover": "assets/Hellish_Quart.webp",
//    "logo": "https://raw.githubusercontent.com/EYELESS-UA/EYELESS-UA.github.io/refs/heads/main/assets/Hellish_Quart_Logo.webp",
//    "status": "planned", "progress": 0,
//    "progress_text": 0,
//    "desc": "Реалістичний файтинг на мечах XVII століття з фізичною моделлю бою. Планується українська локалізація інтерфейсу.",
//    "desc_en": "Realistic 17th century sword fighting game with physics-based combat. Ukrainian UI localization planned.",
//    "github": "https://github.com/EYELESS-UA/Hellish-Quart-Ukrainian-localizationhttps://github.com/EYELESS-UA/Hellish-Quart-Ukrainian-localization/releases/download/test/Hellish-Quart-Ukrainian-localization.7z",
//    "cta": { "type": "link",
//    "label": "Завантажити",
//    "label_en": "Download",
//    "url": "https://github.com/EYELESS-UA/Hellish-Quart-Ukrainian-localization",
//    "primary": true },
//    "videos": [],
//    "gallery": [] 
//    },

//  { "id": "Thief",
//    "title": "Thief",
//    "cover": "assets/Thief.webp",
//    "logo": "assets/Thief_logo.webp",
//    "status": "planned",
//    "progress": 0,
//    "progress_text": 0,
//    "progress_textures": 0,
//    "desc": "Стелс-екшен у готичному місті з атмосферою темного фентезі. Планується повна українська локалізація тексту та текстур.",
//    "desc_en": "Stealth action in a gothic city with dark fantasy atmosphere. Full Ukrainian localization of text and textures planned.",
//    "github": "",
//    "cta": { "type": "link",
//    "label": "Завантажити",
//    "label_en": "Download",
//    "url": "",
//    "primary": true },
//    "videos": [],
//    "gallery": ["assets/Thief.webp"] 
//    },

    { "id": "SWTFU2",
    "title": "Star Wars: The Force Unleashed II",
    "cover": "assets/SWTFU2.webp",
    "logo": "assets/SWTFU2_Logo.webp",
    "status": "planned",
    "progress": 100,
    "progress_text": 100,
    "progress_fonts": 0,
    "desc": "Екшен від третьої особи у всесвіті Зоряних Воєн. Продовження історії таємного учня Дарта Вейдера з видовищними боями на світлових мечах та силових здібностях. Планується українська локалізація всіх текстів гри.",
    "desc_en": "Third-person action game set in the Star Wars universe. Continuation of Darth Vader's secret apprentice story with spectacular lightsaber combat and Force abilities. Ukrainian localization of all game texts planned.",
    "github": "https://github.com/EYELESS-UA/SWTFU2-Ukrainian-localization",
    "lkb": "https://github.com/EYELESS-UA/SWTFU2-Ukrainian-localization",
    "cta": { "type": "link",
    "label": "Завантажити",
    "label_en": "Download",
    "url": "https://github.com/EYELESS-UA/SWTFU2-Ukrainian-localization",
    "primary": true },
    "videos": [ "https://www.youtube.com/watch?v=2h8HAT4tLyU" ],
    "gallery": ["assets/screenshot/SWTFU2/screenshot_00.png", "assets/screenshot/SWTFU2/screenshot_01.png", "assets/screenshot/SWTFU2/screenshot_02.png", "assets/screenshot/SWTFU2/screenshot_03.png"] 
    },

//    { "id": "Dishonored",
//    "title": "Dishonored",
//    "cover": "assets/Dishonored.webp",
//    "logo": "assets/Dishonored_Logo.webp",
//    "status": "planned",
//    "progress": 0,
//    "progress_text": 0,
//    "desc": "Екшен від третьої особи у всесвіті Зоряних Воєн. Продовження історії таємного учня Дарта Вейдера з видовищними боями на світлових мечах та силових здібностях. Планується українська локалізація всіх текстів гри.",
//    "desc_en": "Third-person action game set in the Star Wars universe. Continuation of Darth Vader's secret apprentice story with spectacular lightsaber combat and Force abilities. Ukrainian localization of all game texts planned.",
//    "github": "",
//    "cta": { "type": "link",
//    "label": "Завантажити",
//    "label_en": "Download",
//    "url": "",
//    "primary": true },
//    "videos": [],
//    "gallery": ["assets/screenshot/Dishonored/screenshot_00.png", "assets/screenshot/Dishonored/screenshot_01.png", "assets/screenshot/Dishonored/screenshot_02.png", "assets/screenshot/Dishonored/screenshot_03.png"] 
//    },
];

// ДАНІ ДОБРОЧИНЦІВ
const benefactorsList = [


  
];
// ДАНІ НОВИН
const newsData = [
  {
    "id": "aow4-progress-dec-2024",
    "date": "2024-12-08",
    "title": "Age of Wonders 4 — локалізація майже готова!",
    "title_en": "Age of Wonders 4 — localization almost complete!",
    "summary": "Переклад досяг 97% готовності. Завершуємо останні правки перед релізом.",
    "summary_en": "Translation has reached 97% completion. Finalizing last adjustments before release.",
    "full_text": "Після тривалого етапу роботи над локалізацією Age of Wonders 4 ми підійшли до фінальної стадії. У проєкті залишилися лише дрібні правки, а також перевірка узгодженості термінології та стилю. Команда вже працює над останніми деталями, щоб реліз вийшов максимально якісним і природним для українського гравця.",
    "full_text_en": "After a long period of work on the Age of Wonders 4 localization, we have reached the final stage. Only minor edits remain, along with a check for terminology and style consistency. The team is already working on the last details so the release is as polished and natural as possible for Ukrainian players.",
    "category": "progress",
    "project_id": "Age-of-Wonders-4"
  },
  {
    "id": "theguild3-release-nov-2024",
    "date": "2024-11-20",
    "title": "The Guild 3 — локалізація випущена!",
    "title_en": "The Guild 3 — localization released!",
    "summary": "Повна українська локалізація The Guild 3 тепер доступна в Steam Workshop.",
    "summary_en": "Full Ukrainian localization of The Guild 3 is now available on Steam Workshop.",
    "full_text": "Локалізація The Guild 3 тепер доступна для завантаження в Steam Workshop. Це стало результатом великої роботи над текстами, діалогами, інтерфейсом і загальною узгодженістю стилю. Ми продовжуємо стежити за реакцією спільноти та зберігаємо відкритість до можливих правок і покращень.",
    "full_text_en": "The Guild 3 localization is now available for download on Steam Workshop. This result came from extensive work on the texts, dialogues, interface, and overall consistency of style. We continue to monitor community feedback and remain open to possible improvements and refinements.",
    "category": "release",
    "project_id": "The-Guild-3"
  },
  {
    "id": "dream-engines-release-aug-2024",
    "date": "2024-08-15",
    "title": "Dream Engines: Nomad Cities готово!",
    "title_en": "Dream Engines: Nomad Cities is ready!",
    "summary": "Завершено роботу над українською локалізацією Dream Engines. Доступно в Steam.",
    "summary_en": "Ukrainian localization of Dream Engines completed. Available on Steam.",
    "full_text": "Dream Engines: Nomad Cities тепер доступна в українській локалізації. Ми завершили переклад основних текстів, інтерфейсу та ключових елементів, щоб гра відчувалася природно для українського гравця. Це важливий крок для нашої команди і ще один проєкт, який допомагає розширювати український контент у світі ігор.",
    "full_text_en": "Dream Engines: Nomad Cities is now available in Ukrainian localization. We completed the translation of the main texts, interface, and key elements so the game feels natural for Ukrainian players. This is an important milestone for our team and another project that helps expand Ukrainian content in the gaming world.",
    "category": "release",
    "project_id": "Dream_Engines_Nomad_Cities"
},
// {
//   "id": "arx-fatalis-release-jul-2024",
//   "date": "2024-07-10",
//   "title": "Arx Fatalis — перший реліз!",
//   "title_en": "Arx Fatalis — first release!",
//   "summary": "Класична RPG Arx Fatalis тепер повністю українською. Перший великий проєкт студії.",
//   "summary_en": "Classic RPG Arx Fatalis is now fully in Ukrainian. First major studio project.",
//   "category": "release",
//   "project_id": "Arx-Libertatis"
// },
// {
//   "id": "studio-launch-jun-2024",
//   "date": "2024-06-01",
//   "title": "Запуск L Games Studio",
//   "title_en": "L Games Studio Launch",
//   "summary": "Офіційний старт нашої команди локалізації. Почали роботу над першими проєктами.",
//   "summary_en": "Official launch of our localization team. Started work on first projects.",
//   "category": "announcement",
//   "project_id": null
// }
];

    // Дані сайтів користувача Команда="open_my_sites"
    const mySites = [
        { name: "Moonscars Wiki", icon: "🌙", url: "mysite/Moonscars Wiki/index.html" },
        { name: "Dice & Bones", icon: "🌙", url: "mysite/Dice & Bones/index.html" },
        { name: "Dice & Bones", icon: "🌙", url: "mysite/Obsidian Test/index.html" },
        { name: "GitHub", icon: "💻", url: "https://github.com/EYELESS-UA" }
    ];
