// ДАНІ ПРОЄКТІВ
const projectsData = [
  { "id": "Age-of-Wonders-4", "title": "Age of Wonders 4", "cover": "assets/Age_of_Wonders_4.webp", "logo": "assets/Age_of_Wonders_4_logo.webp", "status": "in-progress", "progress": 97, "progress_text": 97, "progress_fonts": 100, "desc": "Інтерфейс і субтитри українською.", "desc_en": "UI and subtitles in Ukrainian.", "cta": { "type": "link", "label": "Завантажити", "label_en": "Download", "url": "https://steamcommunity.com/sharedfiles/filedetails/?id=3391786639", "primary": true }, "videos": [] },
  { "id": "Arx-Libertatis", "title": "Arx Fatalis", "cover": "assets/Arx_Fatalis.webp", "logo": "assets/Arx_Fatalis_logo.webp", "status": "done", "progress": 100, "progress_text": 100, "desc": "Інтерфейс і субтитри українською.", "desc_en": "UI and subtitles in Ukrainian.", "cta": { "type": "link", "label": "Завантажити", "label_en": "Download", "url": "https://github.com/EYELESS-UA/Arx-Libertatis-Ukrainian-localization", "primary": true }, "videos": [] },
//  { "id": "SWTFU2", "title": "Star Wars: The Force Unleashed II", "cover": "assets/SWTFU2.webp", "logo": "assets/SWTFU2_logo.webp", "status": "done", "progress": 100, "progress_text": 100, "desc": "Інтерфейс і субтитри українською.", "desc_en": "UI and subtitles in Ukrainian.", "cta": { "type": "link", "label": "Завантажити", "label_en": "Download", "url": " # ", "primary": true }, "videos": [] },
  { "id": "AgeofWondersPlanetfall", "title": "Age of Wonders Planetfall", "cover": "assets/Age_of_Wonders_Planetfall.webp", "logo": "assets/Age_of_Wonders_Planetfall_logo.webp", "status": "planned", "progress": 0, "progress_text": 0, "desc": "Інтерфейс і субтитри українською.", "desc_en": "UI and subtitles in Ukrainian.", "cta": { "type": "link", "label": "Завантажити", "label_en": "Download", "url": "https://steamcommunity.com/sharedfiles/filedetails/?id=3391786639", "primary": true }, "videos": [] },
//{ "id": "HellishQuart", "title": "Hellish Quart", "cover": "assets/Hellish_Quart.webp", "logo": "assets/Hellish_Quart_logo.webp", "status": "planned", "progress": 0, "progress_text": 0, "desc": "Інтерфейс і субтитри українською.", "desc_en": "UI and subtitles in Ukrainian.", "cta": { "type": "link", "label": "Завантажити", "label_en": "Download", "url": "https://steamcommunity.com/sharedfiles/filedetails/?id=3391786639", "primary": true }, "videos": [] },
  { "id": "The-Guild-3", "title": "The Guild 3", "cover": "assets/TheGuild3.webp", "logo": "assets/TheGuild3_Logo.webp", "status": "done", "progress": 100, "progress_text": 100,   "desc": "Опис", "desc_en": "desc", "cta": { "type": "link", "label": "Завантажити", "label_en": "Download", "url": "https://steamcommunity.com/sharedfiles/filedetails/?id=3507960492", "primary": true }, "steam": "", "videos": [""] }
];

// ДАНІ ДОБРОЧИНЦІВ
const benefactorsList = [
   
];
